<?xml version="1.0"?>
<!DOCTYPE resume
[
<!ELEMENT resume (qualification+,personalDetails+,skillSet+)>
<!ELEMENT qualification (btech+)>
<!ELEMENT btech (yearOfQualification,university)>
<!ELEMENT yearOfQualification (#PCDATA)>
<!ELEMENT university (#PCDATA)>
<!ELEMENT personalDetails (name,email,phone)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT skillSet (technical+)>
<!ELEMENT technical (programmingLanguage+,software+)>
<!ELEMENT programmingLanguage (name+)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name id CDATA #REQUIRED>
<!ELEMENT software (name+)>
]>
<resume>
	<qualification>
		<btech>
			<yearOfQualification>2020</yearOfQualification>
			<university>Presidency University</university>
		</btech>
	</qualification>
	<personalDetails>
		<name id="0">Newt</name>
		<email>idk@gmail.com</email>
		<phone>1802391319</phone>
	</personalDetails>
	<skillSet>
		<technical>
			<programmingLanguage>
				<name id="1">Java</name>
				<name id="2">Python</name>
				<name id="3">C++</name>
			</programmingLanguage>
			<software>
				<name id="1">Unity 3D</name>
				<name id="2">Premiere Pro</name>
				<name id="3">After Effects</name>
			</software>
		</technical>
	</skillSet>
</resume>
